---
micronaut:
  server:
    port: ${PORT:8081}
  application:
    name: test
  io:
    watch:
      paths: src/main
      restart: true
jackson:
  bean-introspection-module: true
datasources:
  default:
    url: jdbc:h2:mem:test;MVCC=TRUE;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    schema-generate: CREATE_DROP
    dialect: H2
jpa:
  default:
    packages-to-scan:
    - 'org.belldj' 
    properties:
      hibernate:
        show_sql: true
        bytecode:
          provider: none
        hbm2ddl:
          auto: update


