---
micronaut:
  server:
    port: ${PORT:8081}
  application:
    name: test
  io:
    watch:
      paths: src/main
      restart: true
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
  security:
    enabled: false 
    endpoints:
      login:
        enabled: true 
      oauth:
        enabled: true 
    token:
      jwt:
        enabled: true 
        signatures:
          secret:
            generator: 
              secret: pleaseChangeThisSecretForANewOne
    ldap:
      default: 
        enabled: true
        context:
          server: 'ldap://ldap.forumsys.com:389'  
          managerDn: 'cn=read-only-admin,dc=example,dc=com'  
          managerPassword: 'password'  
        search:
          base: "dc=example,dc=com"  
        groups:
          enabled: true  
          base: "dc=example,dc=com"
jackson:
  bean-introspection-module: true
datasources:
  default:
    url: ${DB_URL:'jdbc:postgresql://localhost/test'}
    driverClassName: org.postgresql.Driver
    username: ${DB_USERNAME:test}
    password: ${DB_PASSWORD:''}
    schema-generate: CREATE_DROP
    dialect: POSTGRES 
jpa:
  default:
    packages-to-scan:
    - 'org.belldj' 
    properties:
      hibernate:
        schema_name: pandora
        show_sql: false
        bytecode:
          provider: none
        hbm2ddl:
          auto: update


